### PR TITLE
Increase size of section reader

### LINKED ISSUE #190: github.com/jboverfelt/hs fails to clone
Hi! Thanks for your work on this - it's been very helpful on systems where it's easier to cross-compile Go than Git! I've run into an issue where cloning a particular repository causes a panic. 

What I Did: `dgit clone https://github.com/jboverfelt/hs`

What I Expected: The repository to be cloned

What Happened Instead:

```
Initialized empty Git repository in /home/joverfelt/hs/.git/
remote: Enumerating objects: 97, done.
Counting objects: 100% (97remote: /97), done.
remote: Compressing objects: 100% (71/71), done.
Indexing objects: 100% (97/97)panic: unexpected EOF

goroutine 1 [running]:
github.com/driusan/dgit/git.PackfileHeader.readEntryDataStream1(0x0, 0xc000000000, 0x869620, 0xc0003c7620, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/packfile.go:163 +0x172
github.com/driusan/dgit/git.PackfileIndexV2.getObjectAtOffset(0x2634f74ff, 0x200000001, 0x200000002, 0x200000002, 0x400000003, 0x400000004, 0x400000004, 0x500000004, 0x600000005, 0x700000006, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/indexpack.go:142 +0x1f6
github.com/driusan/dgit/git.(*Client).getPackedObject(0xc000090360, 0xc000076600, 0x52, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0x7a8c39f7, 0x0, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:189 +0x1ff
github.com/driusan/dgit/git.(*Client).getObject(0xc000090360, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0x7a8c39f7, 0x0, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:229 +0x1c6
github.com/driusan/dgit/git.(*Client).GetObject(0xc000090360, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0xc07a8c39f7, 0x0, 0x6, 0x0, 0xc0003c7470)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:209 +0x44
github.com/driusan/dgit/git.expandGitTreeIntoIndexesRecursive(0xc000090360, 0xae4e9f0981723150, 0xe9c9c6a5f643975f, 0xc03192f353, 0x0, 0x0, 0x31000001, 0x0, 0x0, 0xae0900, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/expandtree.go:66 +0x561
github.com/driusan/dgit/git.expandGitTreeIntoIndexes(0xc000090360, 0x869f80, 0xc00008d3c0, 0xc000000001, 0x40db88, 0x30, 0x7c3740, 0x10dadd01, 0xc0003c7290)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/expandtree.go:30 +0x166
github.com/driusan/dgit/git.(*Index).ResetIndex(0xc0003c7290, 0xc000090360, 0x869f80, 0xc00008d3c0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/index.go:689 +0x4f
github.com/driusan/dgit/git.ReadTree(0xc000090360, 0x10100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x869f80, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/readtree.go:618 +0x387
github.com/driusan/dgit/git.ResetMode(0xc000090360, 0x1000000, 0x869f60, 0xc00008d0a0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/reset.go:124 +0x29e
github.com/driusan/dgit/git.Reset(0xc000090360, 0x1000000, 0x0, 0x0, 0x0, 0xb1, 0x2b1)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/reset.go:64 +0x827
github.com/driusan/dgit/git.Clone(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/clone.go:135 +0x9e8
github.com/driusan/dgit/cmd.Clone(0x0, 0xc000082080, 0x1, 0x1, 0xffffffffffffffff, 0x869480)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/cmd/clone.go:60 +0x52a
main.main()
	/home/joverfelt/gospace/src/github.com/driusan/dgit/main.go:199 +0x440b
```

I was able to reproduce this on both netbsd/amd64 and linux/amd64. I should note that I can't find another repository that causes this issue. BTW, I'll be sending a PR for some minor netbsd syscall fixes unrelated to this issue.

### PR DESCRIPTION
**Pull request by driusan**
The assumption made that a compressed file shouldn't take
any more than three times more than the size of the data
that it represents made in readEntryDataStream1 turns out
to be wrong.

In https://github.com/jboverfelt/hs it turns out to be using
12 bytes on disk to represent 3 bytes of data. According to
"git verify-pack -v" with the official git client the blob
representing the .gitignore (Sha1, Size, On Disk Size, File Offset)
is:

a6ba4f4157c01634d78ea9883d4aaa9af7398c7a blob   3 12 829

This shrinks the fudge factor (for performance reasons), but adds
a minimum size of 512 bytes for the ReaderAt, since small objects
are more likely to encounter degenerate cases for compression.

Fixes #190.

### CODE REVIEW

File: git/indexpack.go [hunk 1]
```diff
@@ -131,13 +131,25 @@ func (idx PackfileIndexV2) getObjectAtOffset(r io.ReaderAt, offset int64, metaOn
...
-	// just determines how much data the SectionReader will read before
-	// returning an EOF.
+	// sz is the uncompressed size, so the total size should usually be
+	// less than sz for the compressed data. It might theoretically be a
+	// little more, but we're generous here since this doesn't allocate
+	// anything but just determines how much data the SectionReader will
+	// read before returning an EOF.
+	//
+	// There is still overhead if the underlying ReaderAt reads more data
+	// than it needs to then discards it, so we assume that it won't
```
Comment (sirnewton01) [inline git/indexpack.go]: Small grammatical error here, I think. It might need a slight rewording.

Comment (driusan) [reply git/indexpack.go]: I'm not seeing it.. where's the grammar error?

Comment (sirnewton01) [reply git/indexpack.go]: "...reads more data than it needs to then discard_s_ it..."

It sounds weird to me. Maybe drop the 's' or maybe "...reads more data than it needs to _and_ then discards it..."

Sorry, very nit picky. Maybe there's no problem.

Comment (driusan) [inline git/indexpack.go]:
```suggestion
	// than it needs to and then discards it, so we assume that it won't
```

can't figure out how to make this edit through github's ui without suggesting changes..
